import { createStyles } from "antd-style"

export const useStyles = createStyles(({ token }) => {
	return {
		topicContainer: {
			width: "100%",
			overflow: "hidden",
			display: "flex",
			flexDirection: "row",
			justifyContent: "center",
			height: "100%",
			gap: token.marginXS,
		},
		messageContainer: {
			width: "480px",
			minWidth: "480px",
			height: "100%",
			overflowX: "hidden",
			overflowY: "hidden",
			position: "relative",
			paddingTop: "42px",
			border: `1px solid ${token.colorBorder}`,
			borderRadius: token.borderRadiusLG,
			backgroundColor: token.magicColorUsages.bg[1],
			"@media (max-width: 768px)": {
				width: "100%",
				minWidth: "unset",
			},
		},
		messageListContainer: {
			padding: "10px 10px 10px 10px",
			width: "100%",
			height: "100%",
			overflowY: "auto",
			overflowX: "hidden",
		},
		messageListHeader: {
			position: "absolute",
			top: 0,
			left: 0,
			right: 0,
			zIndex: 1,
			height: "42px",
			fontWeight: 600,
			fontSize: "16px",
			color: token.magicColorUsages.text[1],
			padding: "10px 20px",
			borderBottom: `1px solid ${token.colorBorder}`,
		},
		leftContainer: {
			width: "300px",
			minWidth: "300px",
			height: "100%",
			borderRadius: token.borderRadiusLG,
			overflowY: "auto",
			display: "flex",
			flexDirection: "column",
			gap: "10px",
		},
		detail: {
			minWidth: "400px",
			flex: 1,
			backgroundColor: token.magicColorUsages.border[1],
			border: `1px solid ${token.colorBorder}`,
			borderRadius: token.borderRadiusLG,
		},
		footer: {
			position: "fixed",
			bottom: 0,
			left: 0,
			right: 0,
			height: "52px",
			padding: "6px",
			backgroundColor: token.magicColorUsages.bg[1],
			border: `1px solid ${token.colorBorder}`,
			borderRadius: token.borderRadiusLG,
			width: `calc(100% - ${token.marginXS * 2}px)`,
			boxSizing: "border-box",
			margin: token.marginXS,
		},
		footerContent: {
			padding: "10px",
			height: "100%",
			display: "flex",
			flexDirection: "row",
			alignItems: "center",
			justifyContent: "space-between",
		},
		footerIcon: {
			width: "32px",
			height: "32px",
		},
		footerLeft: {
			display: "flex",
			alignItems: "center",
			gap: token.marginXS,
			fontWeight: 400,
		},
		magicIcon: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			backgroundColor: token.magicColorUsages.bg[1],
			borderRadius: token.borderRadiusLG,
		},
		attachmentList: {
			height: "100%",
			backgroundColor: token.magicColorUsages.bg[1],
			display: "flex",
			flexDirection: "column",
			overflowY: "hidden",
			padding: "10px",
		},
		taskData: {
			flex: 1,
			backgroundColor: token.magicColorUsages.bg[1],
			border: `1px solid ${token.colorBorder}`,
			borderRadius: token.borderRadiusLG,
			overflowX: "hidden",
		},
		item: {
			fontSize: "14px",
			height: 40,
			display: "flex",
			alignItems: "center",
			gap: 4,
			borderRadius: 8,
			padding: 10,
			color: token.magicColorUsages.text[1],
		},
		title: {
			fontSize: "12px",
			color: token.colorTextSecondary,
			fontWeight: 400,
			marginBottom: 10,
		},
		menuContainer: {
			marginTop: 10,
			borderBottom: `1px solid ${token.colorBorder}`,
		},
		icon: {
			width: "20px",
			height: "20px",
		},
	}
})
