# 使用 Playwright 基础镜像
FROM dtyq/super-magic-python-base-image

# 设置工作目录
WORKDIR /app

# 复制并安装项目依赖
COPY requirements.txt .

# 安装依赖
RUN pip install -r requirements.txt

# 安装沙箱环境依赖
COPY requirements_sandbox.txt .
RUN pip install -r requirements_sandbox.txt

# 更新环境变量路径
ENV PATH="/usr/local/bin:${PATH}"

COPY . .

# 获取Git commit ID并保存到环境变量
ARG GIT_COMMIT_ID="未知"
ENV GIT_COMMIT_ID=${GIT_COMMIT_ID}

EXPOSE 8000
EXPOSE 8002

CMD ["python3", "main.py", "start", "ws-server"]
